import { db } from "./db";
import * as schema from "@shared/schema";

const categories = ["UI Kits", "Templates", "Plugins", "AI Tools", "Code Scripts", "Mobile Apps"];

const sampleProducts = [
  {
    title: "Modern Dashboard UI Kit",
    description: "A comprehensive UI kit with 200+ components for building modern dashboards. Includes dark mode support, responsive layouts, and customizable themes. Perfect for SaaS applications, admin panels, and data visualization projects.",
    shortDescription: "200+ components for modern dashboards with dark mode",
    category: "UI Kits",
    price: "49.00",
    image: "/placeholder-product-1.jpg",
    author: "DesignStudio",
    rating: "4.9",
    downloads: 1240,
    isFeatured: true,
    tags: ["dashboard", "admin", "ui-kit", "react"],
    licenseType: "Standard License",
    fileSize: "45 MB",
    version: "2.1.0",
  },
  {
    title: "Premium Landing Page Template",
    description: "High-converting landing page template with 15+ sections. Built with Next.js and Tailwind CSS. Includes hero sections, pricing tables, testimonials, and more. Fully responsive and SEO optimized.",
    shortDescription: "High-converting Next.js landing page with 15+ sections",
    category: "Templates",
    price: "39.00",
    image: "/placeholder-product-2.jpg",
    author: "WebCraft",
    rating: "4.8",
    downloads: 980,
    isFeatured: true,
    tags: ["landing-page", "nextjs", "tailwind", "seo"],
    licenseType: "Extended License",
    fileSize: "12 MB",
    version: "1.5.0",
  },
  {
    title: "E-commerce Mobile UI Kit",
    description: "Complete mobile app UI kit for e-commerce applications. 150+ screens covering product browsing, cart management, checkout flow, and user profiles. Available in Figma and Sketch formats.",
    shortDescription: "150+ mobile screens for e-commerce apps",
    category: "UI Kits",
    price: "59.00",
    image: "/placeholder-product-3.jpg",
    author: "MobileFirst",
    rating: "5.0",
    downloads: 756,
    isFeatured: false,
    tags: ["mobile", "ecommerce", "figma", "sketch"],
    licenseType: "Standard License",
    fileSize: "89 MB",
    version: "3.0.0",
  },
  {
    title: "SaaS Website Template",
    description: "Professional SaaS website template with authentication, pricing pages, documentation, and blog. Built with React and includes Stripe integration for payments. Fully customizable and well-documented.",
    shortDescription: "Complete SaaS website with auth and payments",
    category: "Templates",
    price: "45.00",
    image: "/placeholder-product-4.jpg",
    author: "TechTemplates",
    rating: "4.7",
    downloads: 1120,
    isFeatured: false,
    tags: ["saas", "react", "stripe", "auth"],
    licenseType: "Standard License",
    fileSize: "28 MB",
    version: "2.0.0",
  },
  {
    title: "AI Content Generator Plugin",
    description: "WordPress plugin that integrates OpenAI to generate blog posts, product descriptions, and marketing copy. Supports multiple AI models and includes advanced customization options.",
    shortDescription: "WordPress AI content generation with OpenAI",
    category: "Plugins",
    price: "79.00",
    image: "/placeholder-product-5.jpg",
    author: "AIPlugins",
    rating: "4.9",
    downloads: 543,
    isFeatured: true,
    tags: ["wordpress", "ai", "openai", "content"],
    licenseType: "Extended License",
    fileSize: "3 MB",
    version: "1.8.0",
  },
  {
    title: "Smart Form Builder",
    description: "Drag-and-drop form builder with conditional logic, file uploads, and payment integration. Export forms to React, Vue, or HTML. Includes validation, multi-step forms, and analytics.",
    shortDescription: "Drag-and-drop form builder with payments",
    category: "AI Tools",
    price: "69.00",
    image: "/placeholder-product-6.jpg",
    author: "FormWizard",
    rating: "4.6",
    downloads: 892,
    isFeatured: false,
    tags: ["forms", "builder", "payments", "validation"],
    licenseType: "Standard License",
    fileSize: "15 MB",
    version: "4.2.0",
  },
  {
    title: "React Animation Library",
    description: "200+ pre-built animations and transitions for React applications. Includes scroll-based animations, hover effects, page transitions, and loading states. TypeScript support included.",
    shortDescription: "200+ animations for React with TypeScript",
    category: "Code Scripts",
    price: "35.00",
    image: "/placeholder-product-7.jpg",
    author: "AnimatePro",
    rating: "4.8",
    downloads: 1456,
    isFeatured: true,
    tags: ["react", "animation", "typescript", "framer-motion"],
    licenseType: "Standard License",
    fileSize: "8 MB",
    version: "3.5.0",
  },
  {
    title: "Mobile Fitness Tracker App",
    description: "Complete fitness tracking app with workout plans, nutrition tracking, and progress analytics. Built with React Native. Includes backend API and database setup guides.",
    shortDescription: "React Native fitness app with backend",
    category: "Mobile Apps",
    price: "89.00",
    image: "/placeholder-product-8.jpg",
    author: "FitAppStudio",
    rating: "4.7",
    downloads: 432,
    isFeatured: false,
    tags: ["react-native", "fitness", "health", "mobile"],
    licenseType: "Extended License",
    fileSize: "156 MB",
    version: "2.3.0",
  },
];

async function seed() {
  console.log("Seeding database...");

  for (const product of sampleProducts) {
    await db.insert(schema.products).values(product);
  }

  console.log("Database seeded successfully!");
}

seed().catch(console.error);
